export interface ITypeAndId {
  type: string | null;
  id: string | null;
}

export const LOCATION_LIST = {
  학생: [
    'Columbia University',
    'New York University',
    'Hunter College',
    'Barnard College',
    'Fordham University',
    'Marymount Manhattan College',
    'Baruch College',
    'The City College of New York',
    'Fashion Institute of Technology',
    'The New School',
    'Yeshiva University - Wilf Campus',
    'Mercy College',
    'Manhattan College',
    'School of Visual Arts',
    'The Juilliard School',
    'Pace University',
    'LaGuardia Community College',
    'CUNY Graduate Center',
    "The King's College",
    'Borough of Manhattan Community College',
    'Queens College',
    'The American Musical and Dramatic Academy',
    'Pratt Institute',
    'Guttman Community College',
    'LIM College - Maxwell Hall',
    'Manhattan School of Music',
    'Boricua College',
    'SUNY Maritime College',
    'New York City College of Technology',
    'ASA College',
    'College of Staten Island',
    'Touro University',
    'Metropolitan College of New York',
    'Brooklyn College',
    'Wagner College',
    'St. Joseph’s University',
    'York College',
    'New York School of Interior Design',
    'New York Film Academy',
    'Lehman College',
    'The New York Conservatory for Dramatic Arts',
    'Vaughn College',
    'Alliance University',
    'College of Mount Saint Vincent',
    'Kingsborough Community College',
    'Queensborough Community College',
    'Medgar Evers College',
    'Monroe College',
    'Bronx Community College',
    'Plaza College',
    'Phillips School of Nursing',
    'American Academy McAllister Institute',
    'Helene Fuld College of Nursing',
    'Iona University',
    'DeVry College',
    'Hostos Community College',
    'Mildred Elley',
    "St. Paul's School of Nursing",
    'Yeshiva of Nitra',
    'Berkeley College',
  ],
  직장인: [
    'Financial District',
    'SoHo',
    'East Village',
    'West Village',
    'Flatiron',
    'Koreatown',
    'Murray Hill',
    'Hells Kitchen',
    'Midtown West',
    'Midtown East',
    'Midtown',
    'Upper West Side',
    'Upper East Side',
    'Jersey City',
    'Hoboken',
    'Weehawken',
    'Edgewater',
    'Palisades Park',
    'Fort Lee',
    'Englewood',
    'Williamsburg',
    'Brooklyn',
    'Long Island City',
    'Astoria',
    'Woodside',
    'Jackson Heights',
    'Elmhurst',
    'Flushing',
  ],
  비공개: ['Prefer not to say'],
};

export const STATUS_LIST = [
  { label: '학생', value: '학생' },
  { label: '직장인', value: '직장인' },
  { label: '비공개', value: '비공개' },
];
